apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
      - name: messaging-app
        image: messaging-app:blue
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
        - name: DB_HOST
        - name: DB_PORT
        - name: SECRET_KEY
        - name: DB_NAME
        - name: DB_USER
        - name: DB_PASSWORD
        - name: VERSION
          value: "blue"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
