apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
  labels:
    app: messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
      - name: messaging-app
        image: messaging-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
        - name: DB_HOST
        - name: DB_PORT
        - name: SECRET_KEY
        - name: DB_NAME
        - name: DB_USER
        - name: DB_PASSWORD
        - name: DB_ROOT_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# Service to expose the Django app
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
  labels:
    app: messaging-app
spec:
  type: ClusterIP
  selector:
    app: messaging-app
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
